server:
  port: 8001

spring:
  datasource:
    username: root
    password: 061966
#    url: jdbc:mysql://121.36.206.19:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # ShardingSphere
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere
    url: jdbc:shardingsphere:classpath:shardingsphere-config-dev.yml
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
      host: 121.36.206.19
      port: 6379
      password: 061966